{"name": "Проверка ошибки при авторизации под несуществующим пользователем", "status": "passed", "start": 1713248464680, "stop": 1713248464991, "uuid": "8246e471-c78a-4400-9b9c-08ac3abd6bde", "historyId": "172973e359714cc626ec8e99b8917fd5", "testCaseId": "172973e359714cc626ec8e99b8917fd5", "fullName": "tests.test_login#test_login_unregistered_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "kekas"}, {"name": "thread", "value": "3496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}